// <auto-generated />
using System;
using DB_First_PostgreSQL_Web_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DB_First_PostgreSQL_Web_Api.Migrations
{
    [DbContext(typeof(DB_First_CanovaContext))]
    partial class DB_First_CanovaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DB_First_PostgreSQL_Web_Api.Models.Department", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("DB_First_PostgreSQL_Web_Api.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DB_First_PostgreSQL_Web_Api.Models.Employee", b =>
                {
                    b.HasOne("DB_First_PostgreSQL_Web_Api.Models.Department", "IdNavigation")
                        .WithOne("Employee")
                        .HasForeignKey("DB_First_PostgreSQL_Web_Api.Models.Employee", "Id")
                        .HasConstraintName("Employee_Id_fkey")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
